### ISSUE TITLE
The sign of the test function does not produce the same curve.

### ISSUE THREAD

**Issue by TamasPoloskei** [bachrathyd/MDBM.jl#16] opened 2019-04-09 10:45 UTC
I recently started to use the MDBM package and found an unexpected behaviour (at least for me). I started with the example function mentioned in the help, then took the sign of the function. I was expecting to get the same solution because the sign function does not change the location of the roots however the results say otherwise, see figure.
I also include a small MWE as well.

```
using MDBM
using PyPlot

pygui(true)
r = 2
expo = 2.
function foo1(x,y)
    x^(expo) + y^(expo) - (r^expo)
end

function foo2(x, y)
    sign(foo1(x, y))
end


lim = 3.
ax1=Axis((-lim):lim,"x") # initial grid in x direction
ax2=Axis((-lim):lim,"y") # initial grid in y direction

mymdbm1 = MDBM_Problem(foo1, [ax1,ax2])
mymdbm2 = MDBM_Problem(foo2, [ax1,ax2])
iteration = 3 #number of refinements (resolution doubling)

solve!(mymdbm1, iteration)
solve!(mymdbm2, iteration)
```

![Figure](https://i.ibb.co/xCMPspb/Figure-1.png "Figure")

**Comment by bachrathyd** [comment] 2019-04-09 15:07
Thank you for your example.
It was caused by the a left division operation, because the
`pinv(A)`
is not the same as 
`inv(a'*a)*a'`
in case of matrices A if `rank(A) < minimum(size(A))`.

It is fixed in the [commit](https://github.com/bachrathyd/MDBM.jl/commit/6edc94e68936920b0a17838cf87915017e999bc4)

**Closed by bachrathyd** 2019-04-09 15:07 UTC
